/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CategoryDAO;
import model.Category;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
/**
 *
 * @author user
 */

public class CategoryFrame extends javax.swing.JFrame {
    
    private final CategoryDAO categoryDAO = new CategoryDAO();
    private HomeFrame home;
    private int selectedId = -1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CategoryFrame.class.getName());

    /**
     * Creates new form CategoryFrame
     */
    public CategoryFrame(HomeFrame home) {
        this.home = home;
        initComponents();
        
        tblKategori.getSelectionModel()
        .addListSelectionListener(evt -> tblKategoriValueChanged(evt));

        loadTable();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelForm = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        panelTombol = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        scrollTable = new javax.swing.JScrollPane();
        tblKategori = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GaleriPintar - Kelola Kategori");
        setSize(new java.awt.Dimension(500, 500));

        panelMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        panelMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelMain.setLayout(new java.awt.BorderLayout());

        panelForm.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Kategori"));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitle.setText("Kelola Kategori");

        lblNama.setText("Nama Kategori :");

        txtNama.setColumns(25);
        txtNama.addActionListener(this::txtNamaActionPerformed);

        panelTombol.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnSimpan.setBackground(new java.awt.Color(0, 153, 0));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        panelTombol.add(btnSimpan);

        btnUbah.setBackground(new java.awt.Color(51, 102, 255));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.setEnabled(false);
        btnUbah.addActionListener(this::btnUbahActionPerformed);
        panelTombol.add(btnUbah);

        btnHapus.setBackground(new java.awt.Color(255, 0, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        panelTombol.add(btnHapus);

        btnReset.setBackground(new java.awt.Color(255, 204, 0));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);
        panelTombol.add(btnReset);

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        panelTombol.add(btnBack);

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(lblNama)
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFormLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(lblTitle)
                                .addGap(118, 184, Short.MAX_VALUE))
                            .addGroup(panelFormLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNama)))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                        .addComponent(panelTombol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(panelTombol, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelMain.add(panelForm, java.awt.BorderLayout.NORTH);

        panelTable.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Kategori"));

        tblKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nama Kategori"
            }
        ));
        tblKategori.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblKategori.setRowHeight(24);
        tblKategori.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollTable.setViewportView(tblKategori);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMain.add(panelTable, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void loadTable() {
        try {
            List<Category> list = categoryDAO.findAll();
            DefaultTableModel model = (DefaultTableModel) tblKategori.getModel();
            model.setRowCount(0);
            for (Category c : list) {
                model.addRow(new Object[]{ c.getName() });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal memuat data: " + e.getMessage(),
                "Error Database", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tblKategoriValueChanged(javax.swing.event.ListSelectionEvent evt) {
        if (evt.getValueIsAdjusting()) return;
        int row = tblKategori.getSelectedRow();
        if (row < 0) return;

        try {
            List<Category> list = categoryDAO.findAll();
            if (row < list.size()) {
                Category cat = list.get(row);
                selectedId = cat.getId();
                txtNama.setText(cat.getName());
                btnUbah.setEnabled(true);
                btnHapus.setEnabled(true);
                btnSimpan.setEnabled(false);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal mengambil data: " + e.getMessage(),
                "Error Database", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String nama = txtNama.getText().trim();
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama kategori tidak boleh kosong!",
                "Validasi", JOptionPane.WARNING_MESSAGE);
            txtNama.requestFocus();
            return;
        }
        try {
            if (categoryDAO.nameExists(nama, -1)) {
                JOptionPane.showMessageDialog(this, "Nama kategori sudah ada!",
                    "Duplikat", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Category cat = new Category(nama);
            if (categoryDAO.insert(cat)) {
                JOptionPane.showMessageDialog(this, "Kategori berhasil disimpan!",
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
                resetForm();
                loadTable();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal menyimpan data: " + e.getMessage(),
                "Error Database", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if (selectedId < 0) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diubah!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String nama = txtNama.getText().trim();
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama kategori tidak boleh kosong!",
                "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            if (categoryDAO.nameExists(nama, selectedId)) {
                JOptionPane.showMessageDialog(this, "Nama kategori sudah digunakan oleh data lain!",
                    "Duplikat", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Category cat = new Category(selectedId, nama);
            if (categoryDAO.update(cat)) {
                JOptionPane.showMessageDialog(this, "Kategori berhasil diubah!",
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
                resetForm();
                loadTable();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal mengubah data: " + e.getMessage(),
                "Error Database", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (selectedId < 0) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus kategori ini?\nSemua gambar dalam kategori ini akan ikut terhapus.",
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            if (categoryDAO.delete(selectedId)) {
                JOptionPane.showMessageDialog(this, "Kategori berhasil dihapus!",
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
                resetForm();
                loadTable();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal menghapus data: " + e.getMessage(),
                "Error Database", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
            resetForm();

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void resetForm() {
        txtNama.setText("");
        selectedId = -1;
        btnSimpan.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        tblKategori.clearSelection();
        txtNama.requestFocus();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelTombol;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tblKategori;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
