/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CategoryDAO;
import dao.ImageDAO;
import model.Category;
import model.Image;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.util.List;
/**
 *
 * @author user
 */
public class ImageFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ImageFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    private final ImageDAO imageDAO = new ImageDAO();
    private final CategoryDAO categoryDAO = new CategoryDAO();

    private HomeFrame home;

    private int selectedId = -1;
    private String selectedPath = "";
    private File selectedFile = null;
    private boolean imageChanged = false;

    public ImageFrame(HomeFrame home) {
        this.home = home;
        initComponents();
        
        tblGambar.getSelectionModel()
        .addListSelectionListener(evt -> tblGambarValueChanged(evt));
        
        loadKategoriCombo();
        loadFilterCombo();
        loadTable(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelKiri = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        lblJudul = new javax.swing.JLabel();
        lblKategori = new javax.swing.JLabel();
        cmbKategori = new javax.swing.JComboBox<>();
        lblDeskripsi = new javax.swing.JLabel();
        lblPathGambar = new javax.swing.JLabel();
        scrollDeskripsi = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        txtPath = new javax.swing.JTextField();
        btnPilihGambar = new javax.swing.JButton();
        panelPreview = new javax.swing.JPanel();
        lblPreview = new javax.swing.JLabel();
        panelTombol = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        panelKanan = new javax.swing.JPanel();
        lblFilter = new javax.swing.JLabel();
        cmbFilter = new javax.swing.JComboBox<>();
        scrollTable = new javax.swing.JScrollPane();
        tblGambar = new javax.swing.JTable();
        lblSearch = new javax.swing.JLabel();
        lblTotalData = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GaleriPintar - Kelola Gambar");
        setSize(new java.awt.Dimension(960, 620));

        panelMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        panelMain.setLayout(new java.awt.BorderLayout());

        panelKiri.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Gambar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Kelola Gambar");

        txtJudul.addActionListener(this::txtJudulActionPerformed);

        lblJudul.setText("Judul :");

        lblKategori.setText("Kategori :");

        cmbKategori.addActionListener(this::cmbKategoriActionPerformed);

        lblDeskripsi.setText("Deskripsi :");

        lblPathGambar.setText("FIle :");

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        scrollDeskripsi.setViewportView(txtDeskripsi);

        txtPath.setEditable(false);
        txtPath.addActionListener(this::txtPathActionPerformed);

        btnPilihGambar.setText("PIlih Gambar");
        btnPilihGambar.addActionListener(this::btnPilihGambarActionPerformed);

        panelPreview.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview Gambar"));

        lblPreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelPreviewLayout = new javax.swing.GroupLayout(panelPreview);
        panelPreview.setLayout(panelPreviewLayout);
        panelPreviewLayout.setHorizontalGroup(
            panelPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPreview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPreviewLayout.setVerticalGroup(
            panelPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPreview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );

        panelTombol.setBorder(javax.swing.BorderFactory.createTitledBorder("Button Aksi"));

        btnSimpan.setBackground(new java.awt.Color(0, 153, 0));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        panelTombol.add(btnSimpan);

        btnUbah.setBackground(new java.awt.Color(51, 102, 255));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.setEnabled(false);
        btnUbah.addActionListener(this::btnUbahActionPerformed);
        panelTombol.add(btnUbah);

        btnHapus.setBackground(new java.awt.Color(255, 0, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        panelTombol.add(btnHapus);

        btnReset.setBackground(new java.awt.Color(255, 204, 0));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);
        panelTombol.add(btnReset);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTitle)
                        .addGroup(panelKiriLayout.createSequentialGroup()
                            .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblJudul)
                                .addComponent(lblKategori)
                                .addComponent(lblDeskripsi)
                                .addComponent(lblPathGambar))
                            .addGap(50, 50, 50)
                            .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtJudul)
                                .addComponent(cmbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scrollDeskripsi)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKiriLayout.createSequentialGroup()
                                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPilihGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(panelPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTombol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJudul))
                .addGap(18, 18, 18)
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKategori)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeskripsi)
                    .addComponent(scrollDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPilihGambar))
                    .addComponent(lblPathGambar))
                .addGap(18, 18, 18)
                .addComponent(panelPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTombol, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panelKanan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Table Gambar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        lblFilter.setText("Tampilkan :");

        cmbFilter.addActionListener(this::cmbFilterActionPerformed);

        tblGambar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Judul", "Kategori", "Deskripsi", "Path Gambar", "Tanggal Dibuat"
            }
        ));
        tblGambar.setRowHeight(24);
        tblGambar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblGambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGambarMouseClicked(evt);
            }
        });
        scrollTable.setViewportView(tblGambar);

        lblSearch.setText("Search :");

        lblTotalData.setText("Total Data : 0");

        txtSearch.addActionListener(this::txtSearchActionPerformed);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelKananLayout = new javax.swing.GroupLayout(panelKanan);
        panelKanan.setLayout(panelKananLayout);
        panelKananLayout.setHorizontalGroup(
            panelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKananLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKananLayout.createSequentialGroup()
                        .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(panelKananLayout.createSequentialGroup()
                        .addComponent(lblFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalData)
                        .addGap(27, 27, 27))))
        );
        panelKananLayout.setVerticalGroup(
            panelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilter)
                    .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch)
                    .addComponent(lblTotalData)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(scrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelKiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelKiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void cmbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKategoriActionPerformed

    private void txtPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPathActionPerformed

    private void btnPilihGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihGambarActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Pilih File Gambar");

        fc.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
            "File Gambar (*.jpg, *.jpeg, *.png, *.gif, *.bmp, *.jfif)",
            "jpg", "jpeg", "png", "gif", "bmp", "jfif"
        ));
        fc.setAcceptAllFileFilterUsed(false);

        int result = fc.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {

            File sourceFile = fc.getSelectedFile();

            selectedFile = sourceFile;
            selectedPath = sourceFile.getAbsolutePath();
            imageChanged = true;

            txtPath.setText(sourceFile.getAbsolutePath());
            showPreview(sourceFile.getAbsolutePath());
        }
    }//GEN-LAST:event_btnPilihGambarActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (!validateForm()) return;

        if (selectedFile == null) {
            JOptionPane.showMessageDialog(this,
                "Silakan pilih gambar terlebih dahulu!",
                "Validasi",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            selectedPath = copyToUploads(selectedFile);

            Category cat = (Category) cmbKategori.getSelectedItem();

            Image img = new Image();
            img.setCategoryId(cat.getId());
            img.setTitle(txtJudul.getText().trim());
            img.setDescription(txtDeskripsi.getText().trim());
            img.setImagePath(selectedPath);

            if (imageDAO.insert(img)) {
                JOptionPane.showMessageDialog(this,
                    "Gambar berhasil disimpan!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

                resetForm();
                refreshAll();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Gagal menyimpan gambar: " + e.getMessage(),
                "Error Database",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if (selectedId < 0) {
            JOptionPane.showMessageDialog(this,
                "Pilih data yang ingin diubah!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!validateForm()) return;

        try {
            Category cat = (Category) cmbKategori.getSelectedItem();

            Image img = new Image();
            img.setId(selectedId);
            img.setCategoryId(cat.getId());
            img.setTitle(txtJudul.getText().trim());
            img.setDescription(txtDeskripsi.getText().trim());

            Image oldImage = imageDAO.findById(selectedId);
            String finalPath = (oldImage != null) ? oldImage.getImagePath() : null;

            if (imageChanged && selectedFile != null) {
                if (oldImage != null) {
                    File oldFile = new File(oldImage.getImagePath());
                    if (oldFile.exists()) {
                        oldFile.delete();
                    }
                }
                finalPath = copyToUploads(selectedFile);
            }

            img.setImagePath(finalPath);

            if (imageDAO.update(img)) {
                JOptionPane.showMessageDialog(this,
                    "Gambar berhasil diubah!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

                imageChanged = false;
                resetForm();
                refreshAll();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Gagal mengubah gambar: " + e.getMessage(),
                "Error Database",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (selectedId < 0) {
            JOptionPane.showMessageDialog(this,
                "Pilih data yang ingin dihapus!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus gambar ini?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            Image oldImage = imageDAO.findById(selectedId);

            if (oldImage != null) {
                File oldFile = new File(oldImage.getImagePath());

                if (oldFile.exists()) {
                    oldFile.delete();
                }
            }

            if (imageDAO.delete(selectedId)) {
                JOptionPane.showMessageDialog(this,
                    "Gambar berhasil dihapus!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

                resetForm();
                refreshAll();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Gagal menghapus data: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed
    
    private void resetForm() {
        txtJudul.setText("");
        txtDeskripsi.setText("");
        txtPath.setText("");

        selectedPath = null;
        selectedFile = null;
        imageChanged = false;

        lblPreview.setIcon(null);
        selectedId = -1;

        if (cmbKategori.getItemCount() > 0)
            cmbKategori.setSelectedIndex(0);

        btnSimpan.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);

        tblGambar.clearSelection();
        txtJudul.requestFocus();
    }
    private void cmbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterActionPerformed
        loadTable(getSelectedFilterCategoryId());
    }//GEN-LAST:event_cmbFilterActionPerformed

    private void tblGambarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGambarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGambarMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        loadTable(getSelectedFilterCategoryId());
    }//GEN-LAST:event_txtSearchKeyReleased
    
    
    private void loadKategoriCombo() {
        cmbKategori.removeAllItems();
        try {
            List<Category> list = categoryDAO.findAll();
            for (Category c : list) cmbKategori.addItem(c);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal memuat kategori: " + e.getMessage(),
                "Error Database", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadFilterCombo() {
        cmbFilter.removeAllItems();
        cmbFilter.addItem(new Category(0, "Semua Kategori"));
        try {
            List<Category> list = categoryDAO.findAll();
            for (Category c : list) cmbFilter.addItem(c);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal memuat filter: " + e.getMessage(),
                "Error Database", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadTable(int categoryId) {
        try {

            String keyword = txtSearch.getText().trim();

            List<Image> list;

            if (keyword.isEmpty()) {
                list = (categoryId == 0)
                        ? imageDAO.findAll()
                        : imageDAO.findByCategoryId(categoryId);
            } else {
                list = imageDAO.search(keyword, categoryId);
            }

            DefaultTableModel model =
                    (DefaultTableModel) tblGambar.getModel();

            model.setRowCount(0);

            for (Image img : list) {
                model.addRow(new Object[]{
                    img.getTitle(),
                    img.getCategoryName(),
                    img.getDescription(),
                    img.getImagePath(),
                    img.getCreatedAt()
                });
            }
            
            lblTotalData.setText("Total Data : " + model.getRowCount());

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                "Gagal memuat data gambar: " + e.getMessage(),
                "Error Database",
                JOptionPane.ERROR_MESSAGE);

        }
    }

    private void tblGambarValueChanged(javax.swing.event.ListSelectionEvent evt) {
        if (evt.getValueIsAdjusting()) return;
        int row = tblGambar.getSelectedRow();
        if (row < 0) return;

        try {
            int filterCatId = getSelectedFilterCategoryId();

            List<Image> list = (filterCatId == 0)
                    ? imageDAO.findAll()
                    : imageDAO.findByCategoryId(filterCatId);

            if (row < list.size()) {
                Image img = list.get(row);

                selectedId = img.getId();
                selectedFile = null;
                selectedPath = img.getImagePath();
                imageChanged = false;

                txtJudul.setText(img.getTitle());
                txtDeskripsi.setText(img.getDescription());
                txtPath.setText(img.getImagePath());

                for (int i = 0; i < cmbKategori.getItemCount(); i++) {
                    Category c = (Category) cmbKategori.getItemAt(i);
                    if (c.getId() == img.getCategoryId()) {
                        cmbKategori.setSelectedIndex(i);
                        break;
                    }
                }

                btnSimpan.setEnabled(false);
                btnUbah.setEnabled(true);
                btnHapus.setEnabled(true);

                showPreview(img.getImagePath());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Gagal membaca data: " + e.getMessage(),
                "Error Database",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private int getSelectedFilterCategoryId() {
        Category selected = (Category) cmbFilter.getSelectedItem();
        return (selected == null) ? 0 : selected.getId();
    }

    private String copyToUploads(File source) throws IOException {
        File uploadsDir = new File("uploads");
        if (!uploadsDir.exists()) uploadsDir.mkdirs();

        String fileName = System.currentTimeMillis() + "_" + source.getName();
        File dest = new File(uploadsDir, fileName);
        Files.copy(source.toPath(), dest.toPath(), StandardCopyOption.REPLACE_EXISTING);
        return dest.getPath();
    }

    private void showPreview(String path) {
        if (path == null || path.isEmpty()) {
            lblPreview.setIcon(null);
            return;
        }

        File file = new File(path);

        if (!file.exists()) {
            lblPreview.setIcon(null);
            return;
        }

        try {
            BufferedImage original = ImageIO.read(file);

            if (original == null) {
                lblPreview.setIcon(null);
                return;
            }

            java.awt.Image scaled = scaleImage(original, 300, 220);

            lblPreview.setIcon(new ImageIcon(scaled));

        } catch (IOException e) {
            lblPreview.setIcon(null);
        }
    }

    private java.awt.Image scaleImage(BufferedImage src, int maxW, int maxH) {
        int w = src.getWidth();
        int h = src.getHeight();
        double ratio = Math.min((double) maxW / w, (double) maxH / h);
        int newW = (int) (w * ratio);
        int newH = (int) (h * ratio);
        return src.getScaledInstance(newW, newH, java.awt.Image.SCALE_SMOOTH);
    }

    private boolean validateForm() {
        if (txtJudul.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Judul tidak boleh kosong!");
            return false;
        }

        if (cmbKategori.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Pilih kategori!");
            return false;
        }

        if (selectedId < 0) {
            if (selectedPath == null || selectedPath.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Pilih gambar terlebih dahulu!");
                return false;
            }
        }

        return true;
    }

    private void refreshAll() {
        loadTable(getSelectedFilterCategoryId());
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPilihGambar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<Category> cmbFilter;
    private javax.swing.JComboBox<Category> cmbKategori;
    private javax.swing.JLabel lblDeskripsi;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblPathGambar;
    private javax.swing.JLabel lblPreview;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalData;
    private javax.swing.JPanel panelKanan;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelPreview;
    private javax.swing.JPanel panelTombol;
    private javax.swing.JScrollPane scrollDeskripsi;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tblGambar;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
