/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.UserDAO;
import model.User;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
/**
 *
 * @author user
 */
public class UserFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserFrame.class.getName());
    
    private final UserDAO userDAO= new UserDAO();
    private HomeFrame home;
    private int selectedId = -1;
    /**
     * Creates new form UserFrame
     */
    
    public UserFrame(HomeFrame home) {
        this.home = home;
        initComponents();
        
        tblUser.getSelectionModel()
        .addListSelectionListener(evt -> tblUserValueChanged(evt));

        loadTable();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelForm = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        panelTombol = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblNomerTelepon = new javax.swing.JLabel();
        txtNomerTelepon = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtDivisi = new javax.swing.JTextField();
        lblDivisi = new javax.swing.JLabel();
        panelTable = new javax.swing.JPanel();
        scrollTable = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        panelMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelMain.setLayout(new java.awt.BorderLayout());

        panelForm.setBorder(javax.swing.BorderFactory.createTitledBorder("Form User"));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitle.setText("Kelola User");

        lblNama.setText("Nama :");

        txtNama.setColumns(25);
        txtNama.addActionListener(this::txtNamaActionPerformed);

        panelTombol.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnSimpan.setBackground(new java.awt.Color(0, 153, 0));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        panelTombol.add(btnSimpan);

        btnUbah.setBackground(new java.awt.Color(51, 102, 255));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.setEnabled(false);
        btnUbah.addActionListener(this::btnUbahActionPerformed);
        panelTombol.add(btnUbah);

        btnHapus.setBackground(new java.awt.Color(255, 0, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        panelTombol.add(btnHapus);

        btnReset.setBackground(new java.awt.Color(255, 204, 0));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);
        panelTombol.add(btnReset);

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        panelTombol.add(btnBack);

        lblNomerTelepon.setText("Nomer Telepon :");

        txtNomerTelepon.setColumns(25);
        txtNomerTelepon.addActionListener(this::txtNomerTeleponActionPerformed);

        lblEmail.setText("Email :");

        txtEmail.setColumns(25);
        txtEmail.addActionListener(this::txtEmailActionPerformed);

        txtDivisi.setColumns(25);
        txtDivisi.addActionListener(this::txtDivisiActionPerformed);

        lblDivisi.setText("Divisi :");

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(lblTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTombol, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomerTelepon)
                            .addComponent(lblEmail)
                            .addComponent(lblDivisi)
                            .addComponent(lblNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama)
                            .addComponent(txtDivisi)
                            .addComponent(txtEmail)
                            .addComponent(txtNomerTelepon))))
                .addContainerGap())
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNama))
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDivisi))
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomerTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomerTelepon))
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(panelTombol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelMain.add(panelForm, java.awt.BorderLayout.NORTH);

        panelTable.setBorder(javax.swing.BorderFactory.createTitledBorder("Data User"));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Divisi", "Nomer Telepon", "Email"
            }
        ));
        tblUser.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblUser.setRowHeight(24);
        tblUser.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        scrollTable.setViewportView(tblUser);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMain.add(panelTable, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void loadTable() {
        try {
            List<User> list = userDAO.findAll();
            DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
            model.setRowCount(0);

            for (User u : list) {
                model.addRow(new Object[]{
                    u.getName(),
                    u.getDivision(),
                    u.getPhone(),
                    u.getEmail()
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal memuat data: " + e.getMessage(),
                "Error Database", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tblUserValueChanged(javax.swing.event.ListSelectionEvent evt) {
        if (evt.getValueIsAdjusting()) return;

        int row = tblUser.getSelectedRow();
        if (row < 0) return;

        try {
            List<User> list = userDAO.findAll();

            if (row < list.size()) {
                User user = list.get(row);

                selectedId = user.getId();

                txtNama.setText(user.getName());
                txtDivisi.setText(user.getDivision());
                txtNomerTelepon.setText(user.getPhone());
                txtEmail.setText(user.getEmail());

                btnUbah.setEnabled(true);
                btnHapus.setEnabled(true);
                btnSimpan.setEnabled(false);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal mengambil data: " + e.getMessage(),
                "Error Database", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String nama = txtNama.getText().trim();
        String divisi = txtDivisi.getText().trim();
        String telepon = txtNomerTelepon.getText().trim();
        String email = txtEmail.getText().trim();

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Nama user tidak boleh kosong!",
                "Validasi",
                JOptionPane.WARNING_MESSAGE);
            txtNama.requestFocus();
            return;
        }

        try {
            if (userDAO.nameExists(nama, -1)) {
                JOptionPane.showMessageDialog(this,
                    "Nama user sudah ada!",
                    "Duplikat",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            User user = new User(nama, divisi, telepon, email);

            if (userDAO.insert(user)) {
                JOptionPane.showMessageDialog(this,
                    "Data user berhasil disimpan!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

                resetForm();
                loadTable();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal menyimpan data: " + e.getMessage(),
                "Error Database",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if (selectedId < 0) {
            JOptionPane.showMessageDialog(this,
                "Pilih data user yang ingin diubah!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nama = txtNama.getText().trim();
        String divisi = txtDivisi.getText().trim();
        String telepon = txtNomerTelepon.getText().trim();
        String email = txtEmail.getText().trim();

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Nama user tidak boleh kosong!",
                "Validasi",
                JOptionPane.WARNING_MESSAGE);
            txtNama.requestFocus();
            return;
        }

        try {
            if (userDAO.nameExists(nama, selectedId)) {
                JOptionPane.showMessageDialog(this,
                    "Nama user sudah digunakan oleh data lain!",
                    "Duplikat",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            User user = new User(selectedId, nama, divisi, telepon, email);

            if (userDAO.update(user)) {
                JOptionPane.showMessageDialog(this,
                    "Data user berhasil diubah!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

                resetForm();
                loadTable();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal mengubah data: " + e.getMessage(),
                "Error Database",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (selectedId < 0) {
            JOptionPane.showMessageDialog(this,
                "Pilih data user yang ingin dihapus!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus data user ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            if (userDAO.delete(selectedId)) {
                JOptionPane.showMessageDialog(this,
                    "Data user berhasil dihapus!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

                resetForm();
                loadTable();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal menghapus data: " + e.getMessage(),
                "Error Database",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void resetForm() {

        txtNama.setText("");
        txtDivisi.setText("");
        txtNomerTelepon.setText("");
        txtEmail.setText("");

        selectedId = -1;

        btnSimpan.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);

        tblUser.clearSelection();

        txtNama.requestFocus();
}
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtNomerTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomerTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomerTeleponActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtDivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDivisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDivisiActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblUserMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel lblDivisi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNomerTelepon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelTombol;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtDivisi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNomerTelepon;
    // End of variables declaration//GEN-END:variables
}
